name: commit-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version-file: "pyproject.toml"

      - name: install dependencies
        run: uv sync --all-extras --dev

      - name: commit check
        run: uv run cz check --rev-range HEAD~1..HEAD
